FROM n8nio/n8n:latest

ARG PGPASSWORD
ARG PGHOST
ARG PGPORT
ARG PGDATABASE
ARG PGUSER
ARG N8N_ENCRYPTION_KEY
ARG TZ
ARG WEBHOOK_URL

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_DATABASE=$PGDATABASE
ENV DB_POSTGRESDB_HOST=$PGHOST
ENV DB_POSTGRESDB_PORT=$PGPORT
ENV DB_POSTGRESDB_USER=$PGUSER
ENV DB_POSTGRESDB_PASSWORD=$PGPASSWORD

ENV N8N_ENCRYPTION_KEY=$N8N_ENCRYPTION_KEY
ENV TZ=${TZ:-Europe/Berlin}
ENV WEBHOOK_URL=$WEBHOOK_URL

CMD ["n8n", "start"]
